# to run in VS Code install REST Client extension

// @baseUrl=http://localhost:5000/api/v4
@baseUrl=http://dev.retailhub.ai/api/v4
@token=authtoken
@language=en


#################################################################################
#################################################################################
###                                                                           ###
###                                 ADVISORY                                  ###
###                                                                           ###
#################################################################################
#################################################################################

#################################################################################
######################          list of all steps          ######################
#################################################################################

###
GET {{baseUrl}}/advisory/steps
Accept-Language: {{language}}
Authorization: Bearer {{token}}

#################################################################################
########################          current step          #########################
#################################################################################

###
GET {{baseUrl}}/advisory/steps/current
Accept-Language: {{language}}
Authorization: Bearer {{token}}

#################################################################################
#########################          change step          #########################
#################################################################################

###
POST {{baseUrl}}/advisory/steps
Accept-Language: {{language}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"newStep": 1
}

###
POST {{baseUrl}}/advisory/steps
Accept-Language: {{language}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"newStep": 2
}

###
POST {{baseUrl}}/advisory/steps
Accept-Language: {{language}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"newStep": 3
}

###
POST {{baseUrl}}/advisory/steps
Accept-Language: {{language}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"newStep": 6
}

#################################################################################
########################          send message          #########################
#################################################################################

###
POST {{baseUrl}}/advisory/message
Accept-Language: {{language}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"message": "Voglio ridurre lo spreco di tempo durante l'attesa in cassa"
}

###
POST {{baseUrl}}/advisory/message
Accept-Language: {{language}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"message": "e come evitare i litigi nella fila?"
}

#################################################################################
##########################          questions          ##########################
#################################################################################

# https://retailhub.ai/survey?token=asdfwqersdfsaga435sfsd87435sdfsfs

# FIXME: interviewee_survey_id e non survey_id
# survey_id:		int >= 1	(required)

###
GET {{baseUrl}}/advisory/questions?survey_id=1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

#################################################################################
#######################          submit answers          ########################
#################################################################################

# TODO: validare bene le risposte
###
POST {{baseUrl}}/advisory/submit
Accept-Language: {{language}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"data": {
		{
			"question_id": 1,
			"answer_id": 3
		},
		{
			"question_id": 1,
			"answer_id": 3
		},
	}
}

#################################################################################
########################          list surveys          #########################
#################################################################################

###
GET {{baseUrl}}/advisory/surveys
Accept-Language: {{language}}
Authorization: Bearer {{token}}

#################################################################################
#################################################################################
###                                                                           ###
###                               INTERVIEWEES                                ###
###                                                                           ###
#################################################################################
#################################################################################

#################################################################################
######################         list interviewees          #######################
#################################################################################

# survey_id:		int >= 1	(default: null)

###
GET {{baseUrl}}/advisory/interviewees
Accept-Language: {{language}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/advisory/interviewees/?survey_id=1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/advisory/interviewees/?survey_id=3
Accept-Language: {{language}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/advisory/interviewees/?survey_id=100
Accept-Language: {{language}}
Authorization: Bearer {{token}}

#################################################################################
#######################       read one interviewee        #######################
#################################################################################

###
GET {{baseUrl}}/advisory/interviewees/1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/advisory/interviewees/100
Accept-Language: {{language}}
Authorization: Bearer {{token}}

#################################################################################
######################         create interviewee         #######################
#################################################################################

###
POST {{baseUrl}}/advisory/interviewees
Accept-Language: {{language}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"first_name": "   Uiop",
	"last_name": "Poiu   ",
	"email": "   uiop@uiop.it   "
}

###
POST {{baseUrl}}/advisory/interviewees
Accept-Language: {{language}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"first_name": "Sixth",
	"last_name": "Smith",
	"email": "sixth.smith@gmail.com"
}

###
POST {{baseUrl}}/advisory/interviewees
Accept-Language: {{language}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"first_name": "Seventh",
	"last_name": "Setti",
	"email": "seventh.setti@gmail.com"
}


#################################################################################
######################         update interviewee         #######################
#################################################################################

###
PUT {{baseUrl}}/advisory/interviewees/5
Accept-Language: {{language}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"first_name": "  Uiop Modified",
	"last_name": "   Poiu Modified    ",
	"email": "uiop.modified@uiop.com     "
}

#################################################################################
######################         delete interviewee         #######################
#################################################################################

###
DELETE {{baseUrl}}/advisory/interviewees/7
Accept-Language: {{language}}
Authorization: Bearer {{token}}

#################################################################################
#####################         confirm interviewees         ######################
#################################################################################

###
POST {{baseUrl}}/advisory/interviewees/confirm
Accept-Language: {{language}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"survey_id": 1,
	"interviewees_ids": [5, 6, 7],
	"message": "There is a survery for you"
}

#################################################################################
#################################################################################
###                                                                           ###
###                            ADVISORY - RESULTS                             ###
###                                                                           ###
#################################################################################
#################################################################################

#################################################################################
######################          completion stats          #######################
#################################################################################

# survey_id:		int >= 1	(required)

###
GET {{baseUrl}}/advisory/results/completion?survey_id=3
Accept-Language: {{language}}
Authorization: Bearer {{token}}

#################################################################################
###################          results by interviewee          ####################
#################################################################################

# company_id:		int >= 0	(default: 0)
# innovation_ids[]:	array		(default: null)
# widget:			int >= 1	(required)

###
GET {{baseUrl}}/advisory/results/by-interviewee?widget_id=1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/advisory/results/by-interviewee?company_id=2&widget_id=1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/advisory/results/by-interviewee?company_id=2&innovation_ids[]=2&widget_id=1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

#################################################################################
######################          results by survey          ######################
#################################################################################

# company_id:		int >= 0	(default: 0)
# innovation_ids[]:	array		(default: null)
# widget:			int >= 1	(required)

###
GET {{baseUrl}}/advisory/results/by-survey?widget_id=1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/advisory/results/by-survey?company_id=2&widget_id=1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/advisory/results/by-survey?company_id=2&innovation_ids[]=2&innovation_ids[]=3&widget_id=1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

#################################################################################
#####################          results by absolute          #####################
#################################################################################

# TODO: innovation_name al posto di innovation_description?

# company_id:		int >= 0	(default: 0)
# innovation_ids[]:	array		(default: null)
# widget:			int >= 1	(required)

###
GET {{baseUrl}}/advisory/results/by-absolute?widget_id=1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/advisory/results/by-absolute?company_id=2&widget_id=1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/advisory/results/by-absolute?company_id=2&innovation_ids[]=2&innovation_ids[]=3&widget_id=1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

#################################################################################
#####################          results histograms          ######################
#################################################################################

# company_id:		int >= 1	(required)
# innovation_id:	int >= 1	(required)

###
GET {{baseUrl}}/advisory/results/histograms?company_id=2&innovation_id=2
Accept-Language: {{language}}
Authorization: Bearer {{token}}

#################################################################################
#####################          stats by innovation          #####################
#################################################################################

# company_id:		int >= 1	(required)
# innovation_id:	int >= 1	(required)

###
GET {{baseUrl}}/advisory/results/by-innovation?company_id=2&innovation_id=2
Accept-Language: {{language}}
Authorization: Bearer {{token}}

#################################################################################
######################          stats by company          #######################
#################################################################################

# per consulente retailhub
# TODO: innovation_name al posto di innovation_description?

# company_ids[]:	array		(default: null)
# innovation_ids[]:	array		(required)
# widget:			int >= 1	(required)

###
GET {{baseUrl}}/advisory/results/by-company?innovation_ids[]=2&innovation_ids[]=3&widget_id=1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/advisory/results/by-company?company_ids[]=2&innovation_ids[]=2&innovation_ids[]=3&widget_id=1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

#################################################################################
###########################          ranking          ###########################
#################################################################################

# innovation_ids[]:			array		(default: null)
# current_innovation_id:	int >= 1	(required, must be in the innovation_ids array)

###
GET {{baseUrl}}/advisory/results/ranking?current_innovation_id=2
Accept-Language: {{language}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/advisory/results/ranking?innovation_ids[]=1&innovation_ids[]=2&innovation_ids[]=3&current_innovation_id=2
Accept-Language: {{language}}
Authorization: Bearer {{token}}


#################################################################################
########################          download csv          #########################
#################################################################################

# company_ids[]:	array		(default: null)
# innovation_ids[]:	array		(required)
# widget:			int >= 1	(required)

###
GET {{baseUrl}}/advisory/results/download?innovation_ids[]=2&innovation_ids[]=3&widget_id=1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/advisory/results/download?company_ids[]=2&innovation_ids[]=2&innovation_ids[]=3&widget_id=1
Accept-Language: {{language}}
Authorization: Bearer {{token}}

